# Generated by Django 4.2.5 on 2023-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='delete_flg',
            field=models.BooleanField(null=True),
        ),
    ]
