# Generated by Django 4.2.5 on 2023-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
