# Generated by Django 4.2.5 on 2023-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
