# Generated by Django 4.2.5 on 2023-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel_file_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
