# Generated by Django 4.2.5 on 2023-11-06 02:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
