# Generated by Django 4.2.6 on 2023-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='url',
            field=models.URLField(),
        ),
    ]
