# Generated by Django 4.2.6 on 2023-11-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productmodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='url',
        ),
    ]
