# Generated by Django 4.2.6 on 2023-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_productmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
