# Generated by Django 4.2.6 on 2023-12-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productmodel_image_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image_promotion',
        ),
    ]
